<?php

use srag\Plugins\Test\Utils\TestTrait;
use srag\DIC\Test\DICTrait;

/**
 * Class ilTestUIHookGUI
 *
 * Generated by SrPluginGenerator v2.8.1
 *
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 */
class ilTestUIHookGUI extends ilUIHookPluginGUI
{

    use DICTrait;
    use TestTrait;

    const PLUGIN_CLASS_NAME = ilTestPlugin::class;


    /**
     * ilTestUIHookGUI constructor
     */
    public function __construct()
    {

    }
}
