<?php

require_once __DIR__ . "/../vendor/autoload.php";

use srag\Plugins\Test\Utils\TestTrait;
use ILIAS\DI\Container;
use srag\CustomInputGUIs\Test\Loader\CustomInputGUIsLoaderDetector;
use srag\DevTools\Test\DevToolsCtrl;
use srag\RemovePluginDataConfirm\Test\PluginUninstallTrait;

/**
 * Class ilTestPlugin
 *
 * Generated by SrPluginGenerator v2.8.1
 *
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 */
class ilTestPlugin extends ilUserInterfaceHookPlugin
{

    use PluginUninstallTrait;
    use TestTrait;

    const PLUGIN_CLASS_NAME = self::class;
    const PLUGIN_ID = "test";
    const PLUGIN_NAME = "Test";
    /**
     * @var self|null
     */
    protected static $instance = null;


    /**
     * ilTestPlugin constructor
     */
    public function __construct()
    {
        parent::__construct();
    }


    /**
     * @return self
     */
    public static function getInstance() : self
    {
        if (self::$instance === null) {
            self::$instance = new self();
        }

        return self::$instance;
    }


    /**
     * @inheritDoc
     */
    public function exchangeUIRendererAfterInitialization(Container $dic) : Closure
    {
        return CustomInputGUIsLoaderDetector::exchangeUIRendererAfterInitialization();
    }


    /**
     * @inheritDoc
     */
    public function getPluginName() : string
    {
        return self::PLUGIN_NAME;
    }


    /**
     * @inheritDoc
     */
    public function updateLanguages(/*?array*/ $a_lang_keys = null) : void
    {
        parent::updateLanguages($a_lang_keys);

        $this->installRemovePluginDataConfirmLanguages();

        DevToolsCtrl::installLanguages(self::plugin());
    }


    /**
     * @inheritDoc
     */
    protected function deleteData() : void
    {
        self::test()->dropTables();
    }


    /**
     * @inheritDoc
     */
    protected function shouldUseOneUpdateStepOnly() : bool
    {
        return false;
    }
}
